// Which program ulw_sandbox runs, and whether it may (sandbox_main.cpp). The caller names a
// program; find_program maps the name to the absolute path the helper was built with
// (sandbox_programs.hpp, generated by CMake from ULW_SANDBOX_FFMPEG and ULW_SANDBOX_FFPROBE), so
// nothing the caller passes ever chooses the file that is executed (docs/adr/0089). check_program
// then vets that path as well: an absolute path in normal form (no "." or ".." component, no
// doubled slash) to a regular file this process may execute, symbolic links followed.
// Header-only for the same reason as seccomp_filter.hpp: the helper links nothing that is
// instrumented, and the tests check the same functions the helper calls.
#pragma once

#include <sys/stat.h>

#include <cerrno>
#include <expected>
#include <fcntl.h>
#include <filesystem>
#include <span>
#include <string>
#include <string_view>
#include <system_error>
#include <unistd.h>
#include <utility>

namespace infra::ffmpeg::sandbox {

struct ProgramRefusal {
    // No such file, a bare name included, which names none; otherwise the file is there but
    // may not be run.
    bool not_found = false;
    std::string reason;
};

// One program a build of the helper may run: the name its caller gives, and the file run for it.
struct Program {
    std::string_view name;
    const char* path = nullptr;
};

// The path `table` holds for `name`. A name with a slash in it is a path, which is never taken
// from the caller, so it is refused (126) even when it is a path the table holds; any other
// name not in the table is not found (127).
[[nodiscard]] inline std::expected<const char*, ProgramRefusal>
find_program(std::span<const Program> table, std::string_view name) {
    if (name.contains('/')) {
        return std::unexpected(ProgramRefusal{
            .reason = "a path, not a program name; only the programs built in are run"});
    }
    for (const Program& program : table) {
        if (program.name == name) {
            return program.path;
        }
    }
    return std::unexpected(
        ProgramRefusal{.not_found = true, .reason = "not a program this helper was built to run"});
}

[[nodiscard]] inline std::expected<void, ProgramRefusal> check_program(std::string_view program) {
    if (!program.contains('/')) {
        return std::unexpected(
            ProgramRefusal{.not_found = true, .reason = "not a path, and no PATH is searched"});
    }
    const std::filesystem::path path(program);
    if (!path.is_absolute()) {
        return std::unexpected(ProgramRefusal{.reason = "not an absolute path"});
    }
    for (const auto& part : path) {
        if (part == "..") {
            return std::unexpected(ProgramRefusal{.reason = "has a .. component"});
        }
    }
    if (path.lexically_normal() != path || program.contains("//")) {
        return std::unexpected(ProgramRefusal{.reason = "not in normal form"});
    }
    struct stat status {};
    if (::stat(path.c_str(), &status) != 0) {
        const int error = errno;
        return std::unexpected(ProgramRefusal{.not_found = error == ENOENT,
                                              .reason = std::generic_category().message(error)});
    }
    if (!S_ISREG(status.st_mode)) {
        return std::unexpected(ProgramRefusal{.reason = "not a regular file"});
    }
    if (::faccessat(AT_FDCWD, path.c_str(), X_OK, AT_EACCESS) != 0) {
        return std::unexpected(ProgramRefusal{.reason = std::generic_category().message(errno)});
    }
    return {};
}

// The file to run for the program `name`: the path `table` holds for it, once check_program has
// passed it. A refusal of that path names it.
[[nodiscard]] inline std::expected<const char*, ProgramRefusal>
program_to_run(std::span<const Program> table, std::string_view name) {
    auto found = find_program(table, name);
    if (!found) {
        return found;
    }
    if (auto checked = check_program(*found); !checked) {
        checked.error().reason = std::string(*found) + ": " + checked.error().reason;
        return std::unexpected(std::move(checked.error()));
    }
    return found;
}

} // namespace infra::ffmpeg::sandbox
