/* Generated by cbindgen from src/lib.rs. Do not edit: see ADR-0039. */

#ifndef ULW_MLS_FFI_BRIDGE_H
#define ULW_MLS_FFI_BRIDGE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// What a call did. Anything but `Ok` leaves every output empty.
typedef enum UlwMlsStatus {
  ULW_MLS_STATUS_OK = 0,
  // A null pointer, an empty or oversized identity or group id, or an empty batch.
  ULW_MLS_STATUS_INVALID_ARGUMENT = 1,
  // The bytes do not decode as the MLS structure this call expects.
  ULW_MLS_STATUS_MALFORMED = 2,
  // The message decodes but the protocol refuses it: a bad signature, another group or
  // epoch, a key package for another ciphersuite, a welcome for someone else.
  ULW_MLS_STATUS_REJECTED = 3,
  // The member to remove is not in the group.
  ULW_MLS_STATUS_NOT_A_MEMBER = 4,
  // This member has been removed from the group; the group can no longer be used.
  ULW_MLS_STATUS_INACTIVE = 5,
  // Crypto or storage failed, or a bug panicked. Free the handles involved.
  ULW_MLS_STATUS_INTERNAL = 6,
} UlwMlsStatus;

// What `ulw_mls_group_process` found in a message.
typedef enum UlwMlsReceived {
  // Plaintext is in the output buffer.
  ULW_MLS_RECEIVED_APPLICATION = 0,
  // Another member's commit, now merged: the group is at the next epoch.
  ULW_MLS_RECEIVED_COMMIT = 1,
  // A proposal, queued for the next commit.
  ULW_MLS_RECEIVED_PROPOSAL = 2,
} UlwMlsReceived;

// A device's MLS identity: its signature key, credential, and the private halves of the key
// packages it has made.
typedef struct UlwMlsClient UlwMlsClient;

// One device's view of one group. Shares its client, which lives until its last group does.
typedef struct UlwMlsGroup UlwMlsGroup;

// Bytes this library allocated. Release with `ulw_mls_buffer_free`.
typedef struct UlwMlsBuffer {
  uint8_t *data;
  size_t len;
} UlwMlsBuffer;

// Borrowed input bytes. `data` may be null when `len` is 0.
typedef struct UlwMlsBytes {
  const uint8_t *data;
  size_t len;
} UlwMlsBytes;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Makes a client whose credential carries `identity`, 1 to 64 bytes.
//
// # Safety
// Pointers must be null or valid for the lengths given; `out` receives a handle to release
// with `ulw_mls_client_free`.
enum UlwMlsStatus ulw_mls_client_new(const uint8_t *identity,
                                     size_t identity_len,
                                     struct UlwMlsClient **out);

// # Safety
// `client` must be null or a handle from `ulw_mls_client_new`, not used afterwards. Groups
// made from it stay usable.
void ulw_mls_client_free(struct UlwMlsClient *client);

// A fresh single-use KeyPackage, serialised as an MLSMessage, for the directory. Its private
// init key stays in the client until a welcome consumes it.
//
// # Safety
// `client` must be a live handle and `out` writable.
enum UlwMlsStatus ulw_mls_client_key_package(const struct UlwMlsClient *client,
                                             struct UlwMlsBuffer *out);

// Starts a group, at epoch 0, with the client as its only member.
//
// # Safety
// `client` must be a live handle, `group_id` valid for `group_id_len` bytes, and `out`
// writable; it receives a handle to release with `ulw_mls_group_free`.
enum UlwMlsStatus ulw_mls_group_create(const struct UlwMlsClient *client,
                                       const uint8_t *group_id,
                                       size_t group_id_len,
                                       struct UlwMlsGroup **out);

// Joins the group a welcome invites the client into, using the key package it names.
//
// # Safety
// As for `ulw_mls_group_create`.
enum UlwMlsStatus ulw_mls_group_join(const struct UlwMlsClient *client,
                                     const uint8_t *welcome,
                                     size_t welcome_len,
                                     struct UlwMlsGroup **out);

// # Safety
// `group` must be null or a handle from this library, not used afterwards.
void ulw_mls_group_free(struct UlwMlsGroup *group);

// Commits adding the members whose key packages are given. The commit stays pending: send
// `commit_out` to the group and `welcome_out` to the new members only once the delivery
// service has accepted the commit for this epoch, then call
// `ulw_mls_group_merge_pending_commit`; if it was refused, call
// `ulw_mls_group_clear_pending_commit`.
//
// # Safety
// `group` must be a live handle, `key_packages` valid for `count` entries, each valid for its
// length, and both outputs writable.
enum UlwMlsStatus ulw_mls_group_add(struct UlwMlsGroup *group,
                                    const struct UlwMlsBytes *key_packages,
                                    size_t count,
                                    struct UlwMlsBuffer *commit_out,
                                    struct UlwMlsBuffer *welcome_out);

// Commits removing the member whose credential carries `identity`. Pending, as for
// `ulw_mls_group_add`.
//
// # Safety
// `group` must be a live handle, `identity` valid for its length and `commit_out` writable.
enum UlwMlsStatus ulw_mls_group_remove(struct UlwMlsGroup *group,
                                       const uint8_t *identity,
                                       size_t identity_len,
                                       struct UlwMlsBuffer *commit_out);

// Applies this member's pending commit: the delivery service accepted it.
//
// # Safety
// `group` must be a live handle.
enum UlwMlsStatus ulw_mls_group_merge_pending_commit(struct UlwMlsGroup *group);

// Drops this member's pending commit: another commit won the epoch.
//
// # Safety
// `group` must be a live handle.
enum UlwMlsStatus ulw_mls_group_clear_pending_commit(struct UlwMlsGroup *group);

// Encrypts an application message for the group's current epoch.
//
// # Safety
// `group` must be a live handle, `plaintext` valid for its length and `out` writable.
enum UlwMlsStatus ulw_mls_group_encrypt(struct UlwMlsGroup *group,
                                        const uint8_t *plaintext,
                                        size_t plaintext_len,
                                        struct UlwMlsBuffer *out);

// Processes a message another member sent to the group. Application messages decrypt into
// `plaintext_out`; commits are merged, since the delivery service has already ordered them;
// proposals are queued. A member never processes its own messages.
//
// # Safety
// `group` must be a live handle, `message` valid for its length, and both outputs writable.
enum UlwMlsStatus ulw_mls_group_process(struct UlwMlsGroup *group,
                                        const uint8_t *message,
                                        size_t message_len,
                                        enum UlwMlsReceived *received,
                                        struct UlwMlsBuffer *plaintext_out);

// The group's current epoch, which the delivery service orders commits by.
//
// # Safety
// `group` must be a live handle and `out` writable.
enum UlwMlsStatus ulw_mls_group_epoch(const struct UlwMlsGroup *group, uint64_t *out);

// How many members the group has as this member sees it.
//
// # Safety
// `group` must be a live handle and `out` writable.
enum UlwMlsStatus ulw_mls_group_member_count(const struct UlwMlsGroup *group, size_t *out);

// # Safety
// `buffer` must be empty or have come from this library, and be released once.
void ulw_mls_buffer_free(struct UlwMlsBuffer buffer);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ULW_MLS_FFI_BRIDGE_H */
